type TFunction = (key: string, options?: Record<string, unknown>) => string

/**
 * Traduce descripciones auto-generadas legacy que contienen "abonos vigentes"
 * hacia la nueva plantilla basada en "plan de mantenimiento".
 * Si la descripción no es legacy, la devuelve tal cual.
 */
export const getTranslatedWorkOrderDescription = (
  descripcion: string | undefined | null,
  t: TFunction,
): string => {
  if (!descripcion) return descripcion as string
  if (!/abonos vigentes/i.test(descripcion)) return descripcion

  // Extrae frecuencia del texto legacy: "Frecuencia: Mensual."
  const match = descripcion.match(/Frecuencia:\s*([^.\n]+)\.?/i)
  let frequencyRaw = match ? match[1].trim() : ""

  // Normaliza y traduce la frecuencia usando el namespace de subscriptions
  const freqKey = frequencyRaw.toLowerCase()
  const freqMap: Record<string, string> = {
    mensual: t("subscriptions.frequency.monthly", { defaultValue: frequencyRaw }),
    monthly: t("subscriptions.frequency.monthly", { defaultValue: frequencyRaw }),
    trimestral: t("subscriptions.frequency.quarterly", { defaultValue: frequencyRaw }),
    quarterly: t("subscriptions.frequency.quarterly", { defaultValue: frequencyRaw }),
    semestral: t("subscriptions.frequency.semiannual", { defaultValue: frequencyRaw }),
    semiannual: t("subscriptions.frequency.semiannual", { defaultValue: frequencyRaw }),
    semestriel: t("subscriptions.frequency.semiannual", { defaultValue: frequencyRaw }),
    anual: t("subscriptions.frequency.annual", { defaultValue: frequencyRaw }),
    annual: t("subscriptions.frequency.annual", { defaultValue: frequencyRaw }),
  }

  const translatedFrequency = freqMap[freqKey] || frequencyRaw || t("subscriptions.frequency.monthly")

  // Usa la nueva plantilla traducida
  return t("workOrders.autoGeneratedDescription", {
    frequency: translatedFrequency,
    defaultValue: descripcion,
  })
}
